import { createClient } from "@/lib/supabase/server";
import { NextRequest } from "next/server";
import {
    success,
    created,
    paginated,
    validationError,
    serverError,
} from "@/lib/api/response";
import {
    authenticateRequest,
    isAuthUser,
    getClientIP,
} from "@/lib/api/auth-guard";
import {
    createOrderSchema,
    orderFilterSchema,
    parseSearchParams,
} from "@/lib/api/validate";

// ─── GET /api/v1/orders ──────────────────────
export async function GET(request: NextRequest) {
    const authResult = await authenticateRequest(request, ["admin", "staff"]);
    if (!isAuthUser(authResult)) return authResult;

    const filterResult = parseSearchParams(
        request.nextUrl.searchParams,
        orderFilterSchema
    );
    if (!filterResult.success) {
        return validationError(filterResult.error.issues.map((e: { message: string }) => e.message).join(", "));
    }

    const { page, limit, status, priority, client_id, search } = filterResult.data as { page: number; limit: number; status?: string; priority?: string; client_id?: string; search?: string };
    const offset = (page - 1) * limit;

    const supabase = await createClient();

    let query = supabase
        .from("orders")
        .select("*, client:clients(id, company_name), creator:profiles!orders_created_by_fkey(id, full_name)", { count: "exact" })
        .eq("is_deleted", false)
        .order("created_at", { ascending: false })
        .range(offset, offset + limit - 1);

    if (status) query = query.eq("status", status);
    if (priority) query = query.eq("priority", priority);
    if (client_id) query = query.eq("client_id", client_id);
    if (search) query = query.ilike("order_number", `%${search}%`);

    const { data, count, error: queryError } = await query;

    if (queryError) {
        console.error("Orders query error:", queryError);
        return serverError(queryError.message);
    }

    return paginated(data || [], { page, limit, total: count || 0 });
}

// ─── POST /api/v1/orders ─────────────────────
export async function POST(request: NextRequest) {
    const authResult = await authenticateRequest(request, ["admin", "staff"]);
    if (!isAuthUser(authResult)) return authResult;

    try {
        const body = await request.json();
        const parsed = createOrderSchema.safeParse(body);
        if (!parsed.success) {
            return validationError(parsed.error.issues.map((e: { message: string }) => e.message).join(", "));
        }

        const { items, ...orderData } = parsed.data;

        // Calculate totals
        const subtotal = items.reduce((sum, item) => {
            const lineTotal = item.quantity * item.unit_price * (1 - (item.discount_percent || 0) / 100);
            return sum + lineTotal;
        }, 0);

        const discountAmount =
            orderData.discount_type === "percent"
                ? subtotal * ((orderData.discount_value || 0) / 100)
                : orderData.discount_value || 0;

        const afterDiscount = subtotal - discountAmount;
        const taxAmount = afterDiscount * ((orderData.tax_rate || 0) / 100);
        const totalAmount = afterDiscount + taxAmount;

        const supabase = await createClient();

        // Insert order (order_number auto-generated by trigger)
        const { data: order, error: orderError } = await supabase
            .from("orders")
            .insert({
                order_number: "", // trigger will set
                client_id: orderData.client_id,
                created_by: authResult.id,
                assigned_to: orderData.assigned_to || null,
                priority: orderData.priority,
                estimated_delivery: orderData.estimated_delivery || null,
                internal_notes: orderData.internal_notes || null,
                discount_type: orderData.discount_type || null,
                discount_value: orderData.discount_value || 0,
                subtotal,
                discount_amount: discountAmount,
                tax_rate: orderData.tax_rate || 0,
                tax_amount: taxAmount,
                total_amount: totalAmount,
            })
            .select()
            .single();

        if (orderError) {
            console.error("Order insert error:", orderError);
            return serverError(orderError.message);
        }

        // Insert line items
        const itemsToInsert = items.map((item, index) => ({
            order_id: order.id,
            product_name: item.product_name,
            sku: item.sku || null,
            quantity: item.quantity,
            unit_price: item.unit_price,
            tax_rate: item.tax_rate || 0,
            discount_percent: item.discount_percent || 0,
            line_total: item.quantity * item.unit_price * (1 - (item.discount_percent || 0) / 100),
            sort_order: index,
        }));

        const { error: itemsError } = await supabase
            .from("order_items")
            .insert(itemsToInsert);

        if (itemsError) {
            console.error("Order items insert error:", itemsError);
        }

        // Insert initial status history
        await supabase.from("order_status_history").insert({
            order_id: order.id,
            from_status: null,
            to_status: "draft",
            changed_by: authResult.id,
            ip_address: getClientIP(request),
        });

        // Audit log
        await supabase.from("audit_logs").insert({
            entity_type: "order",
            entity_id: order.id,
            action: "create",
            new_data: order,
            performed_by: authResult.id,
            ip_address: getClientIP(request),
        });

        // Fetch complete order
        const { data: completeOrder } = await supabase
            .from("orders")
            .select("*, items:order_items(*), client:clients(id, company_name)")
            .eq("id", order.id)
            .single();

        return created(completeOrder);
    } catch (err) {
        console.error("Create order error:", err);
        return serverError();
    }
}
